Resources:
    DynamoDB:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: account
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
              - AttributeName: "account_id"
                AttributeType: "N"
            KeySchema:
              - AttributeName: "account_id"
                KeyType: "HASH"
